//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace site1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnYeniGelenler
    {
        public int id { get; set; }
        public string YeniGelenKitapAdı { get; set; }
        public string KitapResmi { get; set; }
        public string Yazarı { get; set; }
        public string Özeti { get; set; }
        public string Fiyatı { get; set; }
    }
}
