//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace site1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcılar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanıcılar()
        {
            this.Sepetim = new HashSet<Sepetim>();
        }
    
        public int id { get; set; }
        public string KULLANICIADI { get; set; }
        public string SIFRE { get; set; }
        public string EMAİL { get; set; }
        public Nullable<System.DateTime> TARİH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepetim> Sepetim { get; set; }
    }
}
