//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace site1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepetim
    {
        public string id { get; set; }
        public Nullable<int> Kulid { get; set; }
    
        public virtual Kullanıcılar Kullanıcılar { get; set; }
    }
}
